import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading={"I'm Shafiq belaroussi"} message={"I'm A Web Developer"} />

      <div className="text-4xl text-center">
        <h1>Featured <span className="hover:border-b-2">Projects</span></h1>
      </div>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
